### ISSUE TITLE
No reason for both initiating and affected player fields in action table

### ISSUE THREAD

**Issue by shadrx** [lena-pl/durak#7]
# Joseph
- [x] ./app/services/apply_attack_action.rb:    if @action.initiating_player == @game_state.player(1)
- [x] ./app/services/apply_attack_action.rb:    elsif @action.initiating_player == @game_state.player(2)
- [x] ./app/services/apply_defend_action.rb:    if @action.initiating_player == @game_state.player(1)
- [x] ./app/services/apply_defend_action.rb:    elsif @action.initiating_player == @game_state.player(2)
- [x] ./app/services/apply_discard_action.rb:    if @action.initiating_player == @game_state.player(1)
- [x] ./app/services/apply_draw_from_deck_action.rb:    if @action.initiating_player == @game_state.player(1)
- [x] ./app/services/apply_draw_from_deck_action.rb:    elsif @action.initiating_player == @game_state.player(2)
- [x] ./app/services/apply_pick_up_from_table_action.rb:    if @action.initiating_player == @game_state.player(1)
- [x] ./app/services/apply_pick_up_from_table_action.rb:    elsif @action.initiating_player == @game_state.player(2)
Binary file ./db/development.sqlite3 matches
- [x] ./db/migrate/20151126040731_create_actions.rb:      t.references :initiating_player, index: true
- [x] ./db/schema.rb:    t.integer  "initiating_player_id"
- [x] ./db/schema.rb:  add_index "actions", ["initiating_player_id"], name: "index_actions_on_initiating_player_id"
Binary file ./db/test.sqlite3 matches
- [x] ./spec/services/apply_attack_action_spec.rb:      let(:attack_action) { Action.new(:kind => :attack, :active_card => card, :initiating_player => player_one) }
- [x] ./spec/services/apply_attack_action_spec.rb:      let(:attack_action) { Action.new(:kind => :attack, :active_card => card, :initiating_player => player_one) }
- [x] ./spec/services/apply_attack_action_spec.rb:      let(:attack_action) { Action.new(:kind => :attack, :active_card => card, :initiating_player => player_two) }
- [x] ./spec/services/apply_attack_action_spec.rb:      let(:attack_action) { Action.new(:kind => :attack, :active_card => card, :initiating_player => player_two) }
- [x] ./spec/services/apply_defend_action_spec.rb:      let(:defend_action) { Action.new(:kind => :defend, :active_card => card, :passive_card => passive_card, :initiating_player => player_one) }
- [x] ./spec/services/apply_defend_action_spec.rb:      let(:defend_action) { Action.new(:kind => :defend, :active_card => card, :passive_card => passive_card, :initiating_player => player_two) }
- [x] ./spec/services/apply_defend_action_spec.rb:      let(:defend_action) { Action.new(:kind => :defend, :active_card => card, :passive_card => passive_card, :initiating_player => player_one) }

# Lena
- [x] ./spec/services/apply_defend_action_spec.rb:      let(:defend_action) { Action.new(:kind => :defend, :active_card => card, :passive_card => passive_card, :initiating_player => player_one) }
- [x] ./spec/services/apply_defend_action_spec.rb:      let(:defend_action) { Action.new(:kind => :defend, :active_card => card, :passive_card => passive_card, :initiating_player => player_two) }
- [x] ./spec/services/apply_discard_action_spec.rb:        let(:discard_action) { Action.new(:kind => :discard, :active_card => attacking_card, :initiating_player => player_one) }
- [x] ./spec/services/apply_discard_action_spec.rb:        let(:discard_action) { Action.new(:kind => :discard, :active_card => attacking_card, :initiating_player => player_two) }
- [x] ./spec/services/apply_discard_action_spec.rb:        let(:another_discard_action) { Action.new(:kind => :discard, :active_card => defending_card, :initiating_player => player_two) }
- [x] ./spec/services/apply_draw_from_deck_action_spec.rb:      let(:draw_from_deck_action) { Action.new(:kind => :draw_from_deck, :active_card => card, :initiating_player => player_one) }
- [x] ./spec/services/apply_draw_from_deck_action_spec.rb:      let(:draw_from_deck_action) { Action.new(:kind => :draw_from_deck, :active_card => card, :initiating_player => player_two) }
- [x] ./spec/services/apply_pick_up_from_table_action_spec.rb:        let(:pickup_from_table_action) { Action.new(:kind => :pick_up_from_table, :active_card => card, :initiating_player => player_one) }
- [x] ./spec/services/apply_pick_up_from_table_action_spec.rb:        let(:pickup_from_table_action) { Action.new(:kind => :pick_up_from_table, :active_card => card, :initiating_player => player_two) }
- [x] ./spec/services/apply_pick_up_from_table_action_spec.rb:      let(:pickup_from_table_action) { Action.new(:kind => :pick_up_from_table, :active_card => card, :initiating_player => player_one) }
- [x] ./spec/test_game.rb:  def deal_card(initiating_player, affected_player, card)
- [x] ./spec/test_game.rb:    create_action(:deal, initiating_player, affected_player, card)
- [x] ./spec/test_game.rb:  def create_action(kind, initiating_player, affected_player, active_card, passive_card = nil)
- [x] ./spec/test_game.rb:    @game_model.actions.create!(kind: kind, initiating_player: initiating_player, affected_player: affected_player,  active_card: active_card, passive_card: passive_card)

**Comment by shadrx** [comment]
./app/services/apply_deal_action.rb:    if @action.affected_player == @game_state.player(1)
./app/services/apply_deal_action.rb:    elsif @action.affected_player == @game_state.player(2)
Binary file ./db/development.sqlite3 matches
./db/schema.rb:    t.integer  "affected_player_id"
./db/schema.rb:  add_index "actions", ["affected_player_id"], name: "index_actions_on_affected_player_id"
Binary file ./db/test.sqlite3 matches
./spec/services/apply_deal_action_spec.rb:      let(:deal_action) { Action.new(:kind => :deal, :active_card => card, :affected_player => player_one) }
./spec/services/apply_deal_action_spec.rb:      let(:deal_action) { Action.new(:kind => :deal, :active_card => card, :affected_player => player_two) }
./spec/services/apply_deal_action_spec.rb:      let(:deal_action) { Action.new(:kind => :deal, :active_card => cards(:hearts_6), :affected_player => player_one) }
./spec/services/apply_deal_action_spec.rb:      let(:deal_action) { Action.new(:kind => :deal, :active_card => cards(:hearts_6), :affected_player => player_two) }
./spec/services/apply_deal_action_spec.rb:      let(:deal_action) { Action.new(:kind => :deal, :active_card => cards(:diamonds_6), :affected_player => player_one) }
- [ ] ./spec/test_game.rb:  def deal_card(initiating_player, affected_player, card)
- [ ]  ./spec/test_game.rb:    create_action(:deal, initiating_player, affected_player, card)
- [ ]  ./spec/test_game.rb:  def create_action(kind, initiating_player, affected_player, active_card, passive_card = nil)
- [ ]  ./spec/test_game.rb:    @game_model.actions.create!(kind: kind, initiating_player: initiating_player, affected_player: affected_player,  active_card: active_card, passive_card: passive_card)

**Comment by lena-pl** [comment]
Fixed
